# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent

# define environment variables here as a map of key: value
env:
  SPRING_PROFILES_ACTIVE: develop
  KEYSTORE_PASS: 123456
  ENCRYPTOR_PASS: MyWeakSecret

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: absences-management
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  metricsPort: 8081
  workDir: /opt/
  keystore: cacerts
  annotations: 
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"  
    prometheus.io/path: '/monitoring/prometheus' 

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx" 
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  paths:
    - /
  hosts:
    - absences-management.jx-sommet-develop.netd.io
  tls:
    - secretName: tls-netd
      hosts:
        - absences-management.jx-sommet-develop.netd.io 

resources:
  limits:
    cpu: 2
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 512Mi

probePath: /monitoring/health
livenessProbe:
  initialDelaySeconds: 45
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 30
readinessProbe:
  periodSeconds: 45
  successThreshold: 1
  timeoutSeconds: 30

ldaps:
  ip: 212.145.245.103
  host: dc-1.lrm.local
  